name: Publish
on:
  push:
    branches:
      - "master"

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install dependencies
        run: |
          yarn -v
          yarn install --immutable

      - name: Apply semver updates (if any)
        run: |
          if yarn auto version; then
            AUTO_VERSION=$(yarn auto version)
            echo "Auto Version: $AUTO_VERSION"
            if [[ $AUTO_VERSION == pre* ]]; then
              yarn lerna version "$AUTO_VERSION" --no-git-tag-version --no-push --yes --preid "$GITHUB_REF"
            elif [[ $AUTO_VERSION ]]; then
              yarn lerna version "$AUTO_VERSION" --no-git-tag-version --no-push --yes
            fi
          else
            echo "Unable to bump version successfully." && exit 1
          fi

      - name: Build
        run: yarn build

      - name: Upload Build Results
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: |
            packages/@magic-ext/*/dist
            packages/@magic-sdk/*/dist
            packages/*/dist

  publish:
    runs-on: ubuntu-20.04
    name: Publish
    needs: build
    environment: production
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install dependencies
        run: |
          yarn -v
          yarn install --immutable

      - name: Download Build Results
        uses: actions/download-artifact@v3
        with:
          name: build-output
          path: packages

      - name: Create Release
        run: yarn auto shipit -v
